### PR TITLE
refactor: Move to riverpod and ObjectBox for state management and storage.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/TokTok/tokhub/1)

### CODE REVIEW

**Review by robinlinden — APPROVED** [review]

**Comment by iphydf** [comment]
I missed some files. Please review again.

**Review by robinlinden — COMMENTED** [review]
The last commit, `cleanup: Give our app a real name`, looks like it does a lot of random things besides giving the app a real name now?

**Comment by iphydf** [comment]
Yeah, squashed a bit. Still doing a lot of stuff :P.

**Review by robinlinden — APPROVED** [review]

**Review by robinlinden — APPROVED** [review]
> Reviewed 8 of 25 files at r1, 20 of 20 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TokTok/tokhub/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @iphydf)

**Pull request merged**
